name: PRINT AWS CREDENTIALS

on:
  workflow_dispatch:
  push:

jobs:
  get-creds:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Assume GitHub Deployment Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::170974506515:role/github-deployment-role
        aws-region: us-west-1
        role-session-name: CredExtractor
        role-external-id: "internal/secrets/id-v2"
        
    - name: Print AWS Credentials
      run: |
        echo "🔑 AWS CREDENTIALS FOR MANUAL USE:"
        echo "=================================="
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
        echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
        echo "AWS_DEFAULT_REGION=us-west-1"
        echo ""
        echo "📋 Export commands for your terminal:"
        echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
        echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" 
        echo "export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
        echo "export AWS_DEFAULT_REGION=us-west-1"
        echo ""
        echo "🎯 Current assumed role identity:"
        aws sts get-caller-identity